parameters:
    # Adds a fallback VARNISH_URL if the env var is not set.
    # This allows you to run cache:warmup even if your
    # environment variables are not available yet.
    # You should not need to change this value.
    env(VARNISH_URL): ''

api_platform:
    name_converter: 'Symfony\Component\Serializer\NameConverter\CamelCaseToSnakeCaseNameConverter'
    mapping:
        paths: ['%kernel.project_dir%/src/Entity']

    # The title of the API.
    title: 'Hello CRM'
    # The description of the API.
    description: 'description'
    version: 1.0.0
    # Varnish integration, remove if unwanted
    http_cache:
        invalidation:
            enabled: true
            varnish_urls: ['%env(VARNISH_URL)%']
        max_age: 0
        shared_max_age: 3600
        vary: ['Content-Type', 'Authorization']
        public: true
    # Mercure integration, remove if unwanted
    mercure:
        hub_url: '%env(MERCURE_SUBSCRIBE_URL)%'

    formats:
        jsonld:   ['application/ld+json']
        json:     ['application/json']
        html:     ['text/html']
        jsonhal:  ['application/hal+json']
    collection:
        pagination:
            # To enable or disable pagination for all resource collections by default.
            enabled: true
            items_per_page: 30
            client_items_per_page: true
            client_enabled: true
            enabled_parameter_name: pagination
            page_parameter_name: _page

    swagger:
        api_keys:
            apiKey:
                name: Authorization
                type: header
